apiVersion: v1
kind: Service
metadata:
  name: owncloud-mysql
  labels:
    app: db
spec:
  selector:
    dc: IN
    app : mysqldb
  clusterIP: None
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name : mysqlweb1
spec :
  replicas : 1
  selector :
    matchLabels:
      dc: IN
      app : mysqldb
  template :
    metadata:
      name: mysqlpod1
      labels:
        dc: IN
        app : mysqldb
    spec:
      containers:
      - name: mysql1
        image: mariadb:10.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: rpass
        ports:
        - containerPort: 3306
          name: mysql1
        volumeMounts:
        - name : owncloud-mariadb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: owncloud-mariadb-storage
        persistentVolumeClaim :
          claimName: owncloud-mariadb-claim