kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-efs
provisioner: eks-activity/aws-efs
---
apiVersion : v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-data-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion : v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-app-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion : v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-config-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion : v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-mariadb-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
